pipeline {
    agent any

    environment {
        APP_NAME = "devops-app"
    }

    stages {

        stage('Clone Code') {
            steps {
                git branch: 'demo', url: 'https://github.com/Santhosh-git26/dev-app.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $APP_NAME -f docker/Dockerfile.'
            }
        }

        stage('Stop Old Container') {
            steps {
                sh '''
                docker rm -f devops-container || true
                '''
            }
        }

        stage('Run Container') {
            steps {
                sh '''
                docker run -d -p 3000:3000 --name devops-container $APP_NAME
                '''
            }
        }

    }
}
