pipeline {
    agent any

    stages {

        stage('Clone Code') {
            steps {
                git branch: 'demo', url: 'https://github.com/Santhosh-git26/dev-app.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t devops-app .'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d -p 3000:3000 devops-app'
            }
        }

    }
} 
